apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-04-29T17:06:55Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: simple-web
  name: simple-web
  namespace: prod
  resourceVersion: "9210"
  uid: 9d9263d0-b202-48f1-b8d3-1a32ddf5eb77
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.0.197.111
  clusterIPs:
  - 10.0.197.111
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32329
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: simple-web
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 20.48.130.11
      ipMode: VIP
