apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-web
  name: simple-web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: simple-web
  type: NodePort
status:
  loadBalancer: {}
